# 03_Numpy
## numpy 的数据类型

In [16]:
import numpy as np

In [17]:
v_list1 = [1,2,3,4,5,6,7,8,9,10]
V = np.array(v_list)  # 把列表变成 naarray 类型（数组类型）
print(v_list)
print(V)  # naarray 类型 与list 对比 显示中 元素之间没有,号隔开
print(type(V))
print(V.shape)  # 查看形状 （几行几列的数据）

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>
(10,)


## .shape 看有几行几列

In [18]:
v_list2 = [10,9,8,7,6,5,4,3,2,1]
M = np.array([v_list1,v_list2])  # 注意要加[] , 把2个列表变成 2维的 naarray 类型
print(M)
print(type(M))
print(M.shape)  # 查看形状 （几行几列的数据）

[[ 1  2  3  4  5  6  7  8  9 10]
 [10  9  8  7  6  5  4  3  2  1]]
<class 'numpy.ndarray'>
(2, 10)


## .size 计算元素个数
## .dtype 查看 元素类型

In [30]:
v_list3 = [10,9,8,7,6,5,4,3,2,1]
H = np.array([v_list1,v_list2,v_list3])
print(H)
print(type(H))
# 查看形状 （几行几列的数据）
# 数据需配对出现，比如v_list1有10个元素，其他list也需要10个，
# 此时 .shape才能显示几行几列，否则不会报错
print(H.shape)  
print(np.shape(H)) # 同上 H.shape
print(np.size(H))  # 计算元素个数
print(H.size)  
print(H.dtype)  # type() 获取数据类型 , .dtype 数组元素的类型，

[[ 1  2  3  4  5  6  7  8  9 10]
 [10  9  8  7  6  5  4  3  2  1]
 [10  9  8  7  6  5  4  3  2  1]]
<class 'numpy.ndarray'>
(3, 10)
(3, 10)
30
30
int32


## H[0,0] 修改数组里元素

In [44]:
# 修改0行0列的元素为2，只能改为数字，否则会报错
H[0,0] = 2
print(H)

[[ 2  2  3  4  5  6  7  8  9 10]
 [10  9  8  7  6  5  4  3  2  1]
 [10  9  8  7  6  5  4  3  2  1]]


## 数据类型会自动转换

In [53]:
v_list_str1 = ['a','b','c']
v_list_str2 = ['a','b','c']
V_str = np.array([v_list_str1,v_list_str2])
V_str[0,0] = 2  # 会自动把2 变成 str类型
print(V_str)   

[['2' 'b' 'c']
 ['a' 'b' 'c']]


## dtype 转换数据类型

In [54]:
# dtype=float 把所有元素变成 float 类型
H_change = np.array([v_list1,v_list2,v_list3],dtype=float)
print(H_change)

[[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [ 10.   9.   8.   7.   6.   5.   4.   3.   2.   1.]
 [ 10.   9.   8.   7.   6.   5.   4.   3.   2.   1.]]


## a[0:2,0:2]  数据切分
- 切 第0和第1排与 第0列和第2列交集的数据

In [77]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print()
a_split1 = a[0:2]  # 切 第0和第1排的数据
print(a_split1)
print()
a_split2 = a[0:2,0:2]  # 切 第0和第1排与 第0列和第2列交集的数据
print(a_split2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [4 5 6]]

[[1 2]
 [4 5]]


### 切片后存储地址一样
- 如修改a_split1里的值，a里的值也会跟着改变

In [79]:
a_split1[0,0] = 8888
print(a_split1)
print()
print(a)

[[8888    2    3]
 [   4    5    6]]

[[8888    2    3]
 [   4    5    6]
 [   7    8    9]]


## 快速生成array
### .full 生成人任意数字数组

In [70]:
a = np.zeros((2,10))  # 注意2个括弧  ，生成0
b = np.ones((5,2))   # 生成 1
c = np.full((5,7),88)  # 生成人任意数字数组
print(a)
print()
print(b)
print()
print(c)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]

[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]

[[88 88 88 88 88 88 88]
 [88 88 88 88 88 88 88]
 [88 88 88 88 88 88 88]
 [88 88 88 88 88 88 88]
 [88 88 88 88 88 88 88]]


### 生成矩阵数据
- identity matrix 单价矩阵取I再变成eye

In [72]:
d = np.eye(10) 
print(d)

[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]]


### 生成随机数据

In [75]:
e = np.random.random((2,3)) # 生成2行3列的数据数组
print(e)

[[ 0.73446255  0.01942219  0.16128676]
 [ 0.73019015  0.12581249  0.94959775]]


### .empty_like生成类似数据

In [145]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
z = np.empty_like(x)  #  
print(z)  

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 0 11 12]]


## 通过index修改数据
### 不改变原有数据

In [86]:
h = np.array([[1,2],[3,4],[5,6]])
print(f'{h}\n')
i = np.array([h[0,1],h[1,1],h[2,0]])
print(f'{i}\n')
i[[0,0]] = 8888
print(f'{i}\n')
print(f'{h}\n')

[[1 2]
 [3 4]
 [5 6]]

[2 4 5]

[8888    4    5]

[[1 2]
 [3 4]
 [5 6]]



### index选取数据小技巧1
- h[[0,1,2],[0,1,0]]) # 取 行[0,1,2] 与 列[0,1,0]的交集数据

In [88]:
h = np.array([[1,2],[3,4],[5,6]])
print(f'{h}\n')
i = np.array(h[[0,1,2],[0,1,0]]) # 取 行[0,1,2] 与 列[0,1,0]的交集数据
print(f'{i}\n')
i[[0,0]] = 8888
print(f'{i}\n')
print(f'{h}\n')

[[1 2]
 [3 4]
 [5 6]]

[1 4 5]

[8888    4    5]

[[1 2]
 [3 4]
 [5 6]]



### index选取数据小技巧2

In [135]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(f'{x}\n')
print(x[0,0:2])  # 0行的 第0和第1个
print(x[2,:])  # index 2行

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[1 2]
[7 8 9]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


### index选取数据附带运算

In [134]:
j = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(f'{j}\n')
k = np.array([0,2,0,1])
l = j[np.arange(4),k]  # 取第0，1，2，3行的，0,2,0,1列的交集
print(f'{l}\n')
j[np.arange(4),k] += 100 # 每取的数据都+100
print(f'{j}\n')

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[ 1  6  7 11]

[[101   2   3]
 [  4   5 106]
 [107   8   9]
 [ 10 111  12]]



## array运算
### bool运算

In [104]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
boolean_m = (m>5)
n = m[m>5]
print(f'{boolean_m}\n')
print(f'{n}\n')

[[False False False]
 [False False  True]
 [ True  True  True]]

[6 7 8 9]



### +-*/四则运算

In [105]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x+y)
print(np.add(x,y))

print(x-y)
print(np.subtract(x,y))

print(x*y)
print(np.multiply(x,y))

print(x/y)
print(np.divide(x,y))

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


### 开方运算

In [108]:
print(np.sqrt(x))  # 只能一个一个数组来

[[ 1.          1.41421356  1.73205081]
 [ 2.          2.23606798  2.44948974]
 [ 2.64575131  2.82842712  3.        ]]


### 点乘余弦定理
- 代数定义
![jupyter](https://gss3.bdstatic.com/7Po3dSag_xI4khGkpoWK1HF6hhy/baike/pic/item/203fb80e7bec54e7b91ac93fb2389b504fc26a19.jpg)
- 几何定义
![jupyter](https://gss2.bdstatic.com/9fo3dSag_xI4khGkpoWK1HF6hhy/baike/pic/item/728da9773912b31b2215893f8018367adab4e1af.jpg)
- 矩阵相乘 (几何定义)
 - 列和行一致才能相乘
 - x第0行与y第0列乘积之和 (1*5+2*7)=19
 - x第0行与y第1列乘积之和 (1*6+2*8)=22
 - x第1行与y第0列乘积之和 (3*5+4*7)=43
 - x第1行与y第1列乘积之和 (3*6+4*8)=50

In [114]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(f'{x}\n')
print(f'{y}\n')
print(x.dot(y))
print(np.dot(x,y)) # 同上

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [115]:
a = np.array([3,0])  # 直角三角形边长a
b = np.array([0,4])  # 直角三角形边长b
print(a.dot(b))   #   向量a*向量b = |a|*|b|*cos90°= 0

0


### .sum求和 .T翻转

In [124]:
x = np.array([[1,2],[3,4]])
y = np.array([[1,2],[3,4],[5,6]])
print(np.sum(x)) # 所有元素相加 1+2+3+4=10
print(np.sum(x,axis=0)) # 每列相加 1+3=4 , 2+4=6
print(np.sum(x,axis=1)) # 每行相加 1+2=3 ，3+4=7
print()
print(f'{x}\n')
print(f'{x.T}\n')
print(f'{y}\n')
print(f'{y.T}\n') # 翻转 PS翻转图片

10
[4 6]
[3 7]

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]

[[1 2]
 [3 4]
 [5 6]]

[[1 3 5]
 [2 4 6]]



### broadcast自动补全

In [148]:
x = np.array([[1,2,3],[4,6,6],[7,8,9]])
y = np.array([[1,0,1]])
z = np.array([[1,0,1],[1,0,1],[1,0,1]])
print(f'{x}\n')
print(f'{x+y}\n')
print(f'{x+z}\n')
# 上面两个运算结果一样

[[1 2 3]
 [4 6 6]
 [7 8 9]]

[[ 2  2  4]
 [ 5  6  7]
 [ 8  8 10]]

[[ 2  2  4]
 [ 5  6  7]
 [ 8  8 10]]



### broadcast思维扩展

In [153]:
x = np.array([[1,2,3],[4,6,6],[7,8,9]])
z = np.empty_like(x) # 创建一个类似x的列表，框架一样
y = np.array([[1,0,1]])
for i in range(3):
    z[i,:]=x[i,:]+ y
print(z)

[[ 2  2  4]
 [ 5  6  7]
 [ 8  8 10]]
