### xpath 语法知识

In [ ]:
 # xpath 节点概念
from lxml import etree

html_str = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>网页名</title>
</head>
<body>
    <div>
        div-text
        <span>span-text</span>
        <a>a-text</a>
        <p>p-text</p>
    </div>
    <table>
        <tr>
            <th>Heading</th>
            <th>Another Heading</th>
        </tr>
        <tr>
            <td>row 1, cell 1</td>
            <td>row 1, cell 2</td>
        </tr>
        table-text-2
    </table>
</body>
</html>
"""

html = etree.HTML(html_str)
print(html.xpath('//body'))

 # xpath语法 contains/id/class
from lxml import etree
html_str = """
<body>
<div class="container">
    <div id="first">
        <div class="one">都市</div>
        <div class="two">德玛西亚</div>
        <div class="two">王牌对王牌</div>
        <a>
            <div class="spe">特殊位置</div>
        </a>
    </div>
    <div id="second">
        <div class="three four">水电费</div>
        <div class="three">说的话房间不开封</div>
        <div class="four">三顿饭黑客技术</div>
    </div>
    <div id="third">
        <div class="three">水电费</div>
        <div class="three">说的话房间开封</div>
    </div>
</div>
</body>
"""
html = etree.HTML(html_str)
print(html.xpath('.//div[@id="first"]'))
print(html.xpath('.//div[@class="three"]/text()'))  # 取class 的值
print(html.xpath('.//div[@id="first"]/div/@class'))
print(html.xpath('.//div[@id="first"]/div[@class="one"]/text()'))  # 取id="first" class="one" 的值
print(html.xpath('.//div[contains(@class,"three")]/text()'))
print(html.xpath('.//div[@class="four"]/text()'))
print(html.xpath('.//div[contains(@class,"four")]/text()'))
print(html.xpath('.//div[contains(@id,"o")]/text()'))
print(html.xpath('.//div[contains(@id,"o")]//text()'))
print(html.xpath('.//div[contains(text(),"水电")]/text()'))


# xpath and or not
from lxml import etree
html_str = """
<body>
<div class="container">
    <div id="first">
        <div class="one">都市</div>
        <div class="two">德玛西亚</div>
        <div class="two three">王牌对王牌</div>
        <a>
            <div class="spe">特殊位置</div>
        </a>
    </div>
    <div id="second">
        <div class="three four">水电费</div>
        <div class="three">说的话房间不开封</div>
        <div class="four">三顿饭黑客技术</div>
    </div>
    <div id="third">
        <div class="three six">水电费</div>
        <div class="three seven">说的话房间开封</div>
    </div>
</div>
</body>
"""
html = etree.HTML(html_str)
print(html.xpath('.//div[contains(@id,"i")]/@id'))
print(html.xpath('.//div[contains(@class,"three") and contains(@class,"six")]/@class'))
print(html.xpath('.//div[contains(@class,"three") and contains(text(),"房间")]/@class'))
print(html.xpath('.//div[contains(@class,"seven") or contains(text(),"德玛西亚")]/@class'))
divs = html.xpath('.//div')
print(len(divs))

divs = html.xpath('.//div[not(@id)]')
print(len(divs))

divs = html.xpath('.//div[not(@id="third")]')
print(len(divs))

# Xpath 规则书写
#     - 越短越好，越精简越好
#     - 不要写很长的xpath规则
#     - 尽可能的分块取值【后面要着重介绍】
#     - 分步操作，不要想着一步到位"

In [ ]:
# xpath 各种用法
from lxml import etree
html_str = """
<body>
<div id="content" class="ui container">

        <table id="contantbody" class="ui striped  table">
            <tr class="1">
                <th>姓名</th>
                <th>性别</th>
                <th>邮箱</th>
                <th>电话</th>
            </tr>
            <tr class="2">
                <td><a href="zhangwei">张伟</a></td>
                <td>男</td>
                <td>zhangwei@haoren.com</td>
                <td>12138-111</td>
            </tr>
            <tr class="3">
                <td><a href="yifei">一菲</a></td>
                <td>女</td>
                <td>yifei@haoren.com</td>
                <td>12138-112</td>
            </tr>
            <tr class="4">
                <td><a href="xiaoxian">小贤</a></td>
                <td>男</td>
                <td>xiaoxian@haoren.com</td>
                <td>12138-113</td>
            </tr>
            <tr class="5">
                <td><a href="meijia">美嘉</a></td>
                <td>女</td>
                <td>meijia@haoren.com</td>
                <td>12138-114</td>
            </tr>
            <tr class="6">
                <td><a href="xiaobu">小布</a></td>
                <td>男</td>
                <td>xiaobu@hundan.com</td>
                <td>12138-115</td>
            </tr>

        </table>
</div>
<div class="two div">two div</div>
</body>
"""

html = etree.HTML(html_str)
print(html.xpath(".//div/@class"))
print(html.xpath(".//div[@id='content']/@class"))
print(html.xpath(".//div[@class='two div']/@class"))
print(html.xpath(".//div[contains(@class,'o')]/@class"))
print(html.xpath('.//table/td')) # 子级 td，没有
print()
print(html.xpath('.//table//td')) # 子孙级 td，有很多
print(html.xpath('.//table//td[text()="男"]/text()'))  # 子孙级 td 检索性别为男的标签
print(html.xpath('.//table//td[text()="男"]/../td//text()')) # 子孙级 td 检索性别为男的tr标签 下的td标签下的所有值
print("好人：",html.xpath('.//table//td[contains(text(),"haoren")]/../td/a/text()'))
print("混蛋：",html.xpath('.//table//td[contains(text(),"hundan")]/../td/a/text()'))
# print(html.xpath('.//table//td[text()="hundan"]/text()'))


# position():比较大小  last():最后一个标签   这两个都是返回当前标签的位置号 ，他们可以进行比较
print(html.xpath(".//table/tr[1]/@class"))  # # 可以用[number]  xpath标签号是从1开始  不是0  ，如果0则返回空
print(html.xpath(".//table/tr[0]/@class"))  # 0则返回空
print(html.xpath(".//table/tr[position()>1]/@class")) # tr位置大于1的所有class
print(html.xpath(".//table/tr[position()!=last()]/@class"))  # 不等于最后一个标签的class
# 常用的：
# following	选取文档中当前节点的结束标签之后的所有节点。
# preceding	选取文档中当前节点的开始标签之前的所有节点。
# ancestor	选取当前节点的所有先辈（父、祖父等）。
# descendant	选取当前节点的所有后代元素（子、孙等）。
# descendant-or-self	选取当前节点的所有后代元素（子、孙等）以及当前节点本身。

# 以下用的少
# namespace	选取当前节点的所有命名空间节点。
# parent	选取当前节点的父节点。
# self	选取当前节点。
# ancestor-or-self	选取当前节点的所有先辈（父、祖父等）以及当前节点本身。
# attribute	选取当前节点的所有属性。
# child	选取当前节点的所有子元素。
# preceding-sibling	选取当前节点之前的所有同级节点。

# print(html.xpath(".//tr/following::*/@class"))  #选取文档中当前节点的结束标签之后的所有节点。tr之后节点的所有class
# print(html.xpath(".//tr/preceding::*/@class"))  #选取文档中当前节点的开始标签之前的所有节点。 tr之前节点的所有class
# print(html.xpath(".//tr/ancestor::*/@class"))   # 选取当前节点的所有先辈（父、祖父等）   tr当前节点的所有class
# print(html.xpath(".//table/descendant::*/@class"))  # 选取当前节点的所有后代元素（子、孙等）。 table当前节点的所有后代元素的 class
# print(html.xpath(".//table/descendant-or-self::*/@class"))  # 选取当前节点的所有后代元素（子、孙等）以及当前节点本身。 table当前节点的所有后代元素的 class 包含本身节点

###  xpath习题

In [ ]:

html_str = """
<body>
    <div class="job">
        <div class="job_title">
            Python爬虫工程师
        </div>

        <div class="job_request">
            985 211 本科 硕士
        </div>
        <div class="salary"><span>20</span>k/m,<span>14</span>薪</div>
        <div class="job_describe">
            java python scrapy linux docker 分布式 javascript
        </div>
        <address>
            北京
        </address>

    </div>
    <hr>


    <div class="job">
        <div class="job_title">
            高级爬虫工程师
        </div>

        <div class="job_request">
            5年工作经验
        </div>
        <div class="salary"> <span>20</span> k/m,<span>15</span>薪</div>
        <div class="job_describe">
            java 电商 分布式爬虫 实时数据抓取
        </div>
        <address>
            北京
        </address>

    </div>
    <hr>
    <div class="job">
        <div class="job_title">
            爬虫工程师
        </div>

        <div class="job_request">
            硕士及以上学历，特别优秀可降低学历要求
        </div>
        <div class="salary"><span>20</span>k/m</div>
        <div class="job_describe">
            Mysql、Redis、Nosql，熟悉elt数据清洗流程及常用方法
        </div>
        <address>
            上海
        </address>

    </div>
    <hr>
    <div class="job">
        <div class="job_title">
            高级爬虫工程师
        </div>

        <div class="job_request">
            本科及以上学历，985/211优先
        </div>
        <div class="salary"><span>8-30</span>k/m</div>
        <div class="job_describe">
            熟悉HTML、JS、正则表达式、Jsoup或jQuery、XPath等，从结构化和非结构化数据中解析数据；
            有验证码破解、数据挖掘、数据仓库搭建经验者优先；
        </div>
        <address>
            北京
        </address>

    </div>
    <hr>

    <div class="job">
        <div class="job_title">
            高级爬虫工程师
        </div>

        <div class="job_request">
            能力者高薪资，不限学历，有大牛指导
        </div>
        <div class="salary"><span>10-50</span>k/m,<span>13</span>薪</div>
        <div class="job_describe">
            1.精通C#或Python或C++或Go语言等爬虫方向开发和应用
            2.具有爬虫系统框架设计能力，以及爬虫项目规划能力
            3.有微信/微博/APP数据抓取优先
        </div>
        <address>
            北京
        </address>

    </div>
    <hr>
    <div class="job">
        <div class="job_title">
            Python开发工程师
        </div>

        <div class="job_request">
            本科及以上学历，985/211优先
        </div>
        <div class="salary"><span>10-50</span>k/m,<span>14</span>薪</div>
        <div class="job_describe">
            django flask tornado flask
            全日制本科学历
            熟练掌握常用数据结构和算法，并能灵活运用
        </div>
        <address>
            北京
        </address>

    </div>
    <hr>
    <div class="job">
        <div class="job_title">
            高级Python开发工程师
        </div>

        <div class="job_request">
            5-10年工作经验
        </div>
        <div class="salary"><span>30</span>k/m,<span>15</span>薪</div>
        <div class="job_describe">
            Python django devops restful postgresql docker ACM
        </div>
        <address>
            上海
        </address>

    </div>
    <hr>
</body>

In [ ]:
from lxml import etree
html = etree.HTML(html_str)

# 列出所有的招聘信息标题，xpath越短越好
job_title1 = html.xpath(".//div[@class='job_title']/text()")
job_title2 = html.xpath(".//div[@class='job']/div[1]/text()")
print(len(job_title1),job_title1)
print(len(job_title2),job_title2)
print()

# 分别统计python爬虫和python开发的岗位数，xpath越短越好
job_pachong = html.xpath(".//div[@class='job_title' and contains(text(),'爬虫')]/text()")
job_kaifa = html.xpath(".//div[@class='job_title' and contains(text(),'开发')]/text()")
print(len(job_pachong),job_pachong)
print(len(job_kaifa),job_kaifa)
print()

# 分别统计不同地区的岗位数，xpath越短越好
job_shanghai = html.xpath(".//address[contains(text(),'上海') ]/text()")
job_beijing = html.xpath(".//address[contains(text(),'北京') ]/text()")
print(len(job_shanghai),job_shanghai)
print(len(job_beijing),job_beijing)
print()

# 查询有多少技术用到了docker技术，xpath越短越好
job_docker = html.xpath(".//div[@class='job_describe' and contains(text(),'docker')]/text()")
print(len(job_docker),job_docker)
print()

# 查询需要本科学历的招聘信息标题
job_benke1 = html.xpath(".//div[@class='job_request'][contains(text(),'本科')]/../div[1]/text()")
job_benke2 = html.xpath(".//div[@class='job_request' and contains(text(),'本科')]/../div[1]/text()")
print(len(job_benke1),job_benke1)
print(len(job_benke2),job_benke2)
print()

# 写明薪资次数的岗位标题
salarys = html.xpath('.//div[@class="salary"]/span[2]/../../div[1]/text()')
print(len(salarys),salarys)

# 未写明自薪资次数的岗位标题
salarys = html.xpath(".//div[@class='salary'][not(span[2])]/../div[1]/text()")
print(len(salarys),salarys)

# 具体薪资的岗位标题
salarys = html.xpath(".//div[@class='salary']/span[1][not(contains(text(),'-'))]/../../div[1]/text()")
print(len(salarys),salarys)
print()

print('-----------------------# 格式化输出全部的招聘信息-----------------------------')
jobs = html.xpath('.//div[@class="job"]')
print(len(jobs))
for job in jobs:
    print(job.xpath(".//div[1]/text()")) # 加 . 表示当前位置
    print(job.xpath(".//div[2]/text()"))
    print(job.xpath(".//div[3]//text()"))
    print(job.xpath(".//div[4]/text()"))
    print(job.xpath(".//address/text()"))
    print('-------------------------------------------------------')


### 爬取淘宝搜索框下的推荐的关键词

In [1]:
import requests
from lxml import etree
headers = {'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36'}
response = requests.get("https://taobao.com",headers = headers)
content = response.content.decode()
html = etree.HTML(content)
txts = html.xpath(".//div[@class='search-hots-fline']/a/text()")
print(f'搜索框下推荐关键词共有:{len(txts)}个')
for txt in txts:
    print(txt)

搜索框下推荐关键词共有:13个
新款连衣裙
四件套
潮流T恤
时尚女鞋
短裤
半身裙
男士外套
墙纸
行车记录仪
新款男鞋
耳机
时尚女包
沙发


### 爬取美女图片

In [2]:
def requests_view(response):     # 定义一个方法：将获取的页面在浏览器中完好的展示出来
    import webbrowser           # 导入 webbrowser 可以在默认浏览器打开url
    request_url = response.url   # 把 提取url并 赋值给变量 request_url
    base_url = '<head><base href="%s">'%(request_url)  #  把request_url的值（url） 放到 %s处   【%s %  %后面的替换%s处】
    base_url = base_url.encode()   # 把上面的base_url 编码成字节类型

    # response.content把源码变成字节类型, .content:返回bytes类型的数据也就是二进制数据   .replace(old,new) old替换成new
    # b"<head>" ： 把 <head> 字符串 转成字节类型
    # 把 <head> 替换成 base_url 的值  （都是字节替换）
    # 替换好的 赋值给 content
    # requests.get()抓下来的源码所有字节，所以用字节类型来转码后替换，不会出错
    content = response.content.replace(b"<head>",base_url)

    # open("文件名","模式")
    # wb模式：wb	以二进制格式打开一个文件只用于写入。如果该文件已存在则打开文件，
    并从开头开始编辑，即原有内容会被删除。如果该文件不存在，创建新文件。
    # 这里创建了一个新的名字叫 tmp.html 的html的文件 并打开
    tem_html = open('tmp.html','wb')

    tem_html.write(content)  #  write()方法用于向文件中写入指定字符串  把 content (已经替换好的源码头) 写入到 tem_html
    tem_html.close()   # close() 方法用于关闭一个已打开的文件
    webbrowser.open_new_tab("tmp.html")  # 用默认浏览器窗口新的标签打开 tmp.html

    # content = response.content.decode()   # .decode() 解码

当前页码：172


NameError: name 'i' is not defined

In [ ]:
import requests
from lxml import etree

headers = {
    'Referer':'http://www.meituba.com', # 增加请求头访问云服务器, 网址即使请求头
    # 增加用户身份识别  network—all 里查看 User-Agent
    'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36'
}

path = 'C:/Users/10746/Desktop/爬下来的美女图片'  # 图片保存的路径

In [ ]:
def download_img(url):  # 下载图片的方法
    imgresp = requests.get(url,headers=headers)
    filename = url.split('/')[-1]  # /作为分割url 最后一块做为文件名
    with open(path + '/' + filename, 'wb') as f:  # 文件名=路径+文件名 （即完整路径）  f为写入的内容
        f.write(imgresp.content)  # 写入二进制的图片

In [ ]:
def parse_page(url):
    resp = requests.get(url,headers=headers) # 伪装头部，赋值给 resp
    html = etree.HTML(resp.content.decode('utf8'))    # 解析resp

    srcs = html.xpath('/html/body/div[4]/div[1]/div[2]/div[1]/div/ul//@src') #xpath取到当前页所有目标图片地址给到srcs
    for src in srcs:       # 检测异常访问不到图片地址就跳过访问下一个
        try:
            download_img(src)
        except:
            print(f'第{i}页，下载失败')
            pass

    next_link = html.xpath('.//div//a[contains(text(),"下一页")]/text()')# 下一页的按钮路径

    if next_link:       # 有下一页按钮返回真，否则返回假
        return True
    else:
        return False

In [13]:
i = 100
def main():
    global i
    base_url = 'http://www.meituba.com/xinggan/list8{}.html'
    while True:
        print(f'当前页码：{i}')
        status = parse_page(base_url.format(i))  # 将url给函数处理，并且函数返回True或False，判断是否继续还是中断死循环
        if status:
            i += 1
        else:
            break
    print('OVER')

In [ ]:
if __name__=="__main__":
    main()

### 设置代理IP 和 cookie

In [ ]:
======================================================
import requests  # 导入库
url = 'https://fanyi.baidu.com/?aldtype=16047#en/zh/'  # 定义URL参数
response = requests.get(url) # 发起请求，并拿到响应，存入response
print(response)  # 打印参数
response.status_code  # 打印状态码

response.text # 响应的文本，就是HTML源码，类型是字符串
response.content # 响应的内容，就是HTML源码，类型是字节
# 上面两个本质是一样的，只是类型不同，text 只适用文本类型，文件类型要用字节


response.headers # 响应的头部信息，通常不用管他
response.request # 请求
response.request.headers # 请求头

import requests
url = 'http://daili.spbeen.com/get_api_json?token=JqC8BlLiOGw038U58ICOEsce&num=1'
proxy = {
    'http':'http://180.171.148.28', # 代理ip
    'https':'https://180.171.148.28'  # 代理ip需支出https协议
}
cookie = {
    'UM_distinctid':'16e4b32ba7f5a-0201dd3d01da88-7711b3e-130980-16e4b32ba80670',
    'CNZZDATA1274503826':'909653764-1575105011-%7C1575105011',
    'csrftoken':'ban6OXRldTx2ExZPkTUT0fqCRQEKzYRJZyKniByuZijjTVcUXidUbtQP8PmsGZGk',
    '_dfesp':'d5o2z69xcntousypbx3nnpbyjxqrajhz'
}  # 提取cookie ，用户登陆信息

# 设置代理IP 和 cookie  timeout单位是秒，默认缺省值是180秒
# response = requests.get(url, proxies = proxy, cookies = cookie,timeout=1)
response = requests.get(url, cookies = cookie,timeout=1)
info = response.json()
print(type(info),info)
print(response.status_code) #  打印状态码

### 爬取赶集网租房信息

In [ ]:
# def requests_view(response): # 可视化源码的方法
#     import webbrowser
#     requests_url = response.url
#     base_url = '<head><base href="%s">'%(requests_url)
#     base_url = base_url.encode()
#     content = response.content.replace(b"<head>",base_url)
#     tem_html = open('tmp.html','wb')
#     tem_html.write(content)
#     tem_html.close()
#     webbrowser.open_new_tab("tmp.html")
#
# requests_view(response)

from sqlalchemy import create_engine # 导入 create_engine包

# 创建引擎,引擎是负责连接的,echo=True  输出日志,False就是不输出
engine = create_engine('sqlite:///ganji_zufang.sqlite',echo=True)

# 导入表格类所需的内容
# Table,Column,Integer,String,ForeignKey
# 表格    列    整形   字符串    外键：用于表格链接表格的
from sqlalchemy import Table,Column,Integer,String,ForeignKey

#导入会话的虚拟类
from sqlalchemy.orm import sessionmaker

# 导入base【表格的基础】
from sqlalchemy.ext.declarative import declarative_base

# 基于引擎，创建会话
DBSession = sessionmaker(bind=engine)

# 会话对象初始化
session = DBSession()

# 为下面class准备的
Base = declarative_base()

# 以上的代码为固定的，不能修改，创建数据库文件及链接使用


class ZuFang(Base):    # 创建一个ZuFang的类，参数为 Base
    __tablename__ = "zufang"   #
    id = Column(Integer,primary_key=True) # primary_key=True 设置id为主键，Integer：整型，Column：列
    title = Column(String(400))   # 把400的字符串类型 给到title
    money = Column(String(400))
    info = Column(String(400))
    people = Column(String(400))
    address1 = Column(String(400))
    address2 = Column(String(400))


    @classmethod  # @classmethod 类就可以不需要实例化，直接类名.方法名()来调用

    def save(cls,data):   # cls固定这么写，如果没有classmethod，就是写self
        session.add(data)  # 添加数据
        session.commit()   # 提交数据
        return data.id    # 返回data的id(主键)

Base.metadata.create_all(engine)

import requests   # 导入获取源码的函数
from lxml import etree  # 导入xpath语法

headers = {
    'Referer':'http://bj.ganji.com/fang1', # 增加请求头访问云服务器, 网址即使请求头
    # 增加用户身份识别  network—all 里查看 User-Agent
    'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36'
}

def parse_data(response,url):  # 定义一个获取目标信息并写到数据库的办法
    html = etree.HTML(response.content.decode())    # 解析response的内容到html
    items = html.xpath('.//div[@class="f-list-item ershoufang-list"]')   #获取html需要的整块信息

    if len(items)==0:
        webbrowser.open_new_tab(url)
        print(response.url)
        strs = input("请输入验证问题，按Enter键继续：")
        if strs.upper()=="ENTER":
            print("继续爬取")
            parse_data(requests.get(url,headers=headers),url)

    for i in items:
        title = i.xpath('.//dd[@class="dd-item title"]/a/text()') # 整块信息里的标题
        money = i.xpath('.//dd[@class="dd-item info"]/div[@class="price"]/span/text()') # 整块信息里的价格
        info = i.xpath('.//dd[@class="dd-item size"]/span/text()') # 整块信息里的  1室1厅1卫  45.00㎡  南向  简单装修  这四个信息
        people = i.xpath('.//dd[@class="dd-item address"]/span/span[@class="address-eara"]/text()')   # 整块信息里的发布人信息
        address1 = i.xpath('.//dd[@class="dd-item address"]/span/a[@class="address-eara"]/text()')   # 整块信息里的地址信息
        address2 = i.xpath('.//dd[@class="dd-item address"]/span/a/span[@class="address-eara"]/text()')   # 整块信息里的地址信息
        zf = ZuFang()  # 创建租房的实例
        zf.title = " ".join(title)  # 把上面获取的目标信息title  给到ZuFang()类里，即写入数据库
        zf.money = " ".join(money)
        zf.info = " ".join(info)
        zf.people = " ".join(people)
        zf.address1 = " ".join(address1)
        zf.address2 = " ".join(address2)
        zf.save(zf)  # 保存

base_url = "http://bj.ganji.com/fang1/o{}"

for i in range(1,100):
    requests_url = base_url.format(i)  # 每一页自动url+1
    response = requests.get(requests_url,headers=headers)   # 给url添加 UA
    print(requests_url,"status_code:",response.status_code) # 打印状态码
    try:   # 如果页面访问成功，但没有返回数据，则跳过
        parse_data(response,request_url)  # 获取目标信息
        # os.remove()
    except:
        print(f'获取信息失败的网址：{request_url}')
        pass

### 爬取网易新闻

In [3]:
import requests  # 请求用的库
from lxml import etree  # 导入解析库
from requests_html import HTMLSession  

In [4]:
url_163news = 'https://news.163.com/'   # 爬取目标的地址
path = r'C:\Users\10746\Desktop\ptthon-test\163news'     # 保存txt文件的路径
headers = {
    'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36'
}      # 请求头
response_163news = requests.get(url_163news,headers = headers)  # 获取网页页面
response_163news.status_code  # 看状态码
response_163news.text  # 看源码文本信息
html = etree.HTML(response_163news.text)  # 信息解码

In [ ]:
urls = html.xpath('.//div[@class="main_center_news"]/div/ul/li/a/@href')  # 获取新闻链接
for url in urls:   # 遍历这些链接
    new_save(url)  # 存储新闻内容到本地

In [ ]:
url_163news = 'https://news.163.com/'   # 爬取目标的地址
session = HTMLSession()
response = session.get(url_163news)
hrefs = response.html.xpath('.//a[@class="na_pic"]/@href')

In [ ]:
print(len(hrefs))
for href in hrefs:   # 遍历这些链接
    print(href)

### requests_html库

In [6]:
from requests_html import HTMLSession
session = HTMLSession()
# url = 'http://www.spbeen.com/tool/request_info/'
url = 'https://huashuguo.tmall.com/index.htm?spm=a220o.1000855.w5002-18327099974.2.22213907tTUohj'
response = session.get(url)
hrefs = response.html.xpath('/html/body/div[1]/div[2]/div/div[1]/div[2]/div[2]/div[1]/div[2]/span/text()')
print(hrefs)
response.html.render()
hrefs = response.html.xpath('/html/body/div[1]/div[2]/div/div[1]/div[2]/div[2]/div[1]/div[2]/span/text()')
print(hrefs)
response.headers
response.request.headers

['4.8']


Future exception was never retrieved
future: <Future finished exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), no reason',)>
Traceback (most recent call last):
  File "C:\Users\10746\Anaconda3\lib\site-packages\websockets\protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "C:\Users\10746\Anaconda3\lib\site-packages\websockets\protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "C:\Users\10746\Anaconda3\lib\site-packages\websockets\protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "C:\Users\10746\Anaconda3\lib\site-packages\websockets\protocol.py", line 1051, in read_frame
    extensions=self.extensions,
  File "C:\Users\10746\Anaconda3\lib\site-packages\websockets\framing.py", line 105, in read
    data = await reader(2)
  File "C:\Users\10746\Anaconda3\lib\asyncio\streams.py", line 666, in readexactly
    rais

['4.8']


{'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.1.2 Safari/603.3.8', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'}

### selenium库

In [7]:
from selenium import webdriver  # 导入页面操作模拟库
from selenium.webdriver.chrome.options import Options  # 导入chrome浏览器可配置选项库
from lxml import etree  # 导入解析库
import faker  # 导入随机生成agent的库

In [8]:
fake = faker.Faker()  # 随机生成agent的库
for i in range(1,20):
    print(fake.user_agent())

Mozilla/5.0 (Android 2.1; Mobile; rv:47.0) Gecko/47.0 Firefox/47.0
Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_6 like Mac OS X) AppleWebKit/532.2 (KHTML, like Gecko) FxiOS/14.6t9051.0 Mobile/57O477 Safari/532.2
Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_10_6 rv:2.0; raj-IN) AppleWebKit/533.20.3 (KHTML, like Gecko) Version/4.0 Safari/533.20.3
Mozilla/5.0 (Android 4.4; Mobile; rv:46.0) Gecko/46.0 Firefox/46.0
Opera/8.91.(Windows NT 5.0; mk-MK) Presto/2.9.164 Version/11.00
Mozilla/5.0 (compatible; MSIE 5.0; Windows 95; Trident/4.0)
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/532.14.4 (KHTML, like Gecko) Version/5.0.2 Safari/532.14.4
Mozilla/5.0 (compatible; MSIE 9.0; Windows 98; Trident/3.0)
Mozilla/5.0 (Windows 98) AppleWebKit/535.1 (KHTML, like Gecko) Chrome/50.0.888.0 Safari/535.1
Mozilla/5.0 (iPhone; CPU iPhone OS 12_4 like Mac OS X) AppleWebKit/533.2 (KHTML, like Gecko) FxiOS/15.3r0918.0 Mobile/59E260 Safari/533.2
Mozilla/5.0 (iPod; U; CPU iPhone OS 4_1 like Mac OS X; af-ZA) Appl

In [ ]:
# 代理IP设置
options = webdriver.ChromeOptions() # 初始化参数
agent_ip = 'http://171.35.146.134:9999'  # 设置代理IP
options.add_argument('--proxy-server={}'.format(agent_ip))  # 参数加入代理IP
br = webdriver.Chrome(options=options)  # 初始化启动谷歌浏览器 并设置代理IP
url_spbeen = 'http://www.spbeen.com/tool/request_info' # 爬取目标2 教程
br.get(url_spbeen)

In [ ]:
url_163 = 'https://study.163.com'
cb = webdriver.Chrome()
cb.get(url_163)

In [ ]:
ux_modal = cb.find_element_by_xpath('.//div[@id="ux-modal"]/div[3]/span')  # 定位同意按钮
ux_modal.click()  # 点击同意按钮
ux_close = cb.find_element_by_xpath('.//a[@class="ux-modal_close"]')   # 定位关闭按钮
ux_close.click()  # 点击关闭按钮
login_register_button = cb.find_element_by_xpath('//*[@id="j-index-nav-login"]') # 定位登陆框
login_register_button.click() # 点击登陆框

In [ ]:
ifranme_element = cb.find_element_by_xpath('//*[@id="x-URS-iframe1575694320727.174"]')  # 定位至iframe标签
cb.switch_to.frame(ifranme_element)  #切换至指定的iframe标签
phone_input = cb.find_element_by_xpath('//*[@id="phoneipt"]') # 定位到账号输入框
phone_input.send_keys('15099919961') # 输入账号/手机号
password_input = cb.find_element_by_xpath('//*[@id="auto-id-1575694321420"]')  # 定位到密码输入框
password_input.send_keys('ads12as445') # 输入密码

In [ ]:
cb.switch_to.default_content()  # 跳出ifranme，回到主页面
phone_input = cb.find_element_by_xpath('//*[@id="phoneipt"]')  # 跳出后，这里就会报错
# br.get(url)  # 获取源码
br.get(url_spbeen)  # 获取源码
apython3 = br.find_element_by_xpath('.//a[contains(text(),"Python3教程")]')  # 定位要新建标签的位置
apython3 # 查看位置数量

In [ ]:
# 打开标签页的操作
link = apython3.get_attribute('href') # 获得完整域名 
new_tab_js = "window.open('{}')".format(link)  # 用新标签打开link的网址的JS代码
br.execute_script(new_tab_js)  # 执行js代码
# 切换标签页，标签页必须通过代码切换，与手动选取无关
handles = br.window_handles  # 获取全部标签页
for handle in handles:
    if handle != br.current_window_handle: # 如果标签不是当前的选中标签页
        br.switch_to.window(handle)  # 切换标签
        break

In [ ]:
br.window_handles # 查看所有标签页
br.switch_to.window(br.window_handles[1]) # 根据标签页列表下标选中切换到的标签页
br.close()  # 关闭 选中的标签页

In [ ]:
# 设置无头浏览器
# chrome_options = Options()  # 初始化
# chrome_options.add_argument('--headless') # 加入无头参数
# br = webdriver.Chrome(chrome_options = chrome_options)  # 初始化启动谷歌浏览器

In [ ]:
# 懒加载，禁止浏览器加载图片
options = webdriver.ChromeOptions()  # 初始化    
prefs = {} # 创建一个字典
prefs['profile.managed_default_content_settings.images'] = 2  # 设置参数
options.add_experimental_option('prefs',prefs)   # 把不加载图片的参数加入 
br2 = webdriver.Chrome(options = options)  # 打开浏览器时参数设置
br2.get(url)  # 打开浏览器
# br.maximize_window()  # 浏览器最大化
# br.quit()  # 退出浏览器

In [ ]:
input_xpath = br.find_element_by_xpath('.//input[@id="mq"]')  # 定位到搜索框
input_xpath.clear() # 清空搜索框里的内容
input_xpath.send_keys('连衣裙')  # 搜索框输入关键词
search_element = br.find_element_by_xpath('//*[@id="mallSearch"]/form/fieldset/div/button')  # 定位搜索点击按钮
search_element.click()  # 点击搜索按钮

In [ ]:
next_button_element = br.find_element_by_xpath(".//a[contains(text(),'下一页')]")  # 定位到下一页按钮
next_button_element.click() # 点击下一页按钮
html_str = br.page_source # 获取当前页面源码
html = etree.HTML(html_str) # 解析源码
products = html.xpath('//*[@id="J_ItemList"]/div') # 获取商品整块信息
print(len(products))  #  查看有多少商品

In [ ]:
html.xpath('.//div[@id="J_ItemList"]/div[1]/div/p[2]/a/@title')
html.xpath("normalize-space(.//div[@id='J_ItemList']/div[1]/div/p[2]/a/text())")
html.xpath('normalize-space(//*[@id="J_ItemList"]/div[1]/div/div[3]/a/text())')

In [26]:
for product in products:
    title_long = product.xpath('normalize-space(.//div/p[2]/a/@title)')  # 长标题
    title_short = product.xpath("normalize-space(.//div/p[2]/a/text())")  # 短标题
    price = product.xpath('normalize-space(.//div/p[1]/em/text())')  # 价格
    shop = product.xpath('normalize-space(.//div/div[3]/a/text())')   # 旺旺名
    monthly_turnover = product.xpath('normalize-space(.//div/p[3]/span[1]/em/text())')  # 月成交
    evaluate = product.xpath('normalize-space(.//div/p[3]/span[2]/a/text())')  # 评价数
    print(shop,title_long,title_short,price,monthly_turnover,evaluate)

NameError: name 'products' is not defined

### 知乎异步评论

In [9]:
import requests
import json
from lxml import etree
url = 'https://www.zhihu.com/api/v4/answers/926107837/root_comments?order=normal&limit=20&offset=0&status=open'
headers = {
    'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36'
}
response_zhihu = requests.get(url,headers=headers)

In [10]:
response_zhihu.status_code

200

In [11]:
info = json.loads(response_zhihu.content.decode('utf-8'))# 获得json的信息,gbk模式解码
print(type(info)) # 信息为字典格式

<class 'dict'>


In [12]:
for data in info['data']:
    print(data['content'])

是，男性没有女性那么敏感，看事情会开一些。但是还是会留下很不好的印象。是吧朋友。
这样的妹子确实，灵魂里就感觉很脏
答主为人正派(๑❛ᴗ❛๑)
这还不算安全问题吗？过程中感染了什么病，男生下半辈子不就毁了？
她可能觉得男人都是饥不择食吧
男孩子在外一定要保护好自己[飙泪笑]
学会一句话就鹦鹉学舌一样到处乱讲乱玩梗以为自己很潮？
我同学跟我讲过，他大一暑假回家同学聚会喝多了，第二天醒来发现被睡了，那女的都不咋熟，他觉得恶心坏了，回去之后又后怕那女的是不是有病，还自己买了药吃，还去体检了一下才放心。
他的意思是我在做白日梦
这其实不是什么幸运的事情。如果你的意思是想女孩主动，那其实也不难，干净整洁早睡早起慢慢来就好。
你是不是觉得女的说自己被猥亵强奸也是在白日做梦啊
但凡你戒过酒，你就不可能说这些胡话。
你觉得这种事情真的很享受吗
男的被性侵，评论就各种阴阳怪气的，简直了，就想象下被罗玉凤强奸，点同理心都么得
她不丑，而且男生也不单单是看脸吧。我嫌弃她的灵魂。
但凡你有一点修养都不至于随意对人开玩笑
按照你这个逻辑，夜店女，陪酒女，以及性工作者甚至有婚前性行为的人应该被剥夺起诉他人强奸罪的权利——伤害小嘛。
总有人不分场合的玩梗，=_=无语
<p>换成答主是女的酒后差点被强奸你会觉得她嫌男的丑吗？这事就是差点被强奸啊</p>
你是生活中没见过长的帅的男的？


### 简书异步评论

In [13]:
url = 'https://www.jianshu.com/shakespeare/notes/55110064/comments?page=1&count=10&author_only=false&order_by=desc'
headers = {
    'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36'
}
response_SimpleBook = requests.get(url,headers=headers)
response_SimpleBook.status_code

200

In [14]:
info = json.loads(response_SimpleBook.content.decode('utf-8'))# 获得json的信息,gbk模式解码

In [15]:
for comment in info['comments']:
    print(comment['compiled_content'])

收藏了！🌹☕
对失去一无所知，仍然往前走。所以我的生活本该如此没有痛苦
谢谢分享🌹
不错
永远，都不要说永远——放牛班的春天
“总有一天 你会不需要轰轰烈烈的爱情 你想要的只是一个不会离开你的人 冷的时候他会给你一件外套 胃里难受的时候他会给你一杯热水 难过的时候他会给你一个拥抱 就这么一直陪在你身边 陪你走过每一段路 不是整天多爱多爱 而是认真的一句 不离开 所以 等到成熟的年纪 若能最后在一起 晚点没关系” ​
名家名句，好文好文。
很喜欢的句子，每句都有感触
梦开始了，一直在心里的人依旧在，无法言语的微笑，这样挺好。梦醒了，想见的人见了就忘了吧！
不甘平凡又终于平凡


### 简书的下拉异步数据

In [16]:
url = 'https://www.jianshu.com'
headers = {
    'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36'
}
response_SimpleBook_home = requests.get(url,headers=headers)
response_SimpleBook_home.status_code

200

In [17]:
response_SimpleBook_home.text

'<!DOCTYPE html>\n<!--[if IE 6]><html class="ie lt-ie8"><![endif]-->\n<!--[if IE 7]><html class="ie lt-ie8"><![endif]-->\n<!--[if IE 8]><html class="ie ie8"><![endif]-->\n<!--[if IE 9]><html class="ie ie9"><![endif]-->\n<!--[if !IE]><!--> <html> <!--<![endif]-->\n\n<head>\n  <meta charset="utf-8">\n  <meta http-equiv="X-UA-Compatible" content="IE=Edge">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0,user-scalable=no">\n\n  <!-- Start of Baidu Transcode -->\n  <meta http-equiv="Cache-Control" content="no-siteapp" />\n  <meta http-equiv="Cache-Control" content="no-transform" />\n  <meta name="applicable-device" content="pc,mobile">\n  <meta name="MobileOptimized" content="width"/>\n  <meta name="HandheldFriendly" content="true"/>\n  <meta name="mobile-agent" content="format=html5;url=https://www.jianshu.com/">\n  <!-- End of Baidu Transcode -->\n\n    <meta name="description"  content="简书是一个优质的创作社区，在这里，你可以任性地创作，一篇短文、一张照片、一首诗、一幅画……我们相信，每个人都是生活中的艺术家，有着无穷的创造力。">\n  

In [18]:
html = etree.HTML(response_SimpleBook_home.text)

In [19]:
lis = html.xpath('.//li')
print(len(lis))

12


In [20]:
for li in lis:
    title = li.xpath('./div[@class="content"]/a/text()')
    print(title)

[]
[]
[]
[]
[]
['提醒女人：男人逃避这些问题，就是爱上了别人']
['脆皮鸡蛋豆腐，鲜嫩滑爽又补钙，老人孩子要多吃']
['从100人裂变15000人的秘籍，你想知道吗？']
['十二星座性格大揭秘（下）']
['女生如何变得更优雅，干货预警！']
['步入中年的男士，为什么不愿意再碰妻子？']
['睡老婆和睡情人的区别']


### 爬取上海二手房信息

In [3]:
import requests
from lxml import etree
url = 'http://bj.ganji.com/ershoufang/'
headers = {
    "User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
}
response = requests.get(url,headers=headers)
html = etree.HTML(response.text)

In [4]:
def write_file(content:str):
    filename = "二手房数据.csv"
    with open(filename, 'a+', encoding='gbk') as file:
        file.write(content)
        file.write('\n')
# w   字符串写
# wb  二进制写
# a+  追加写入

In [5]:
divs = html.xpath('.//div[@class="f-main-list"]/div/div')
for div in divs:
    title = div.xpath('./dl/dd[1]/a/@title')
    title = [t.replace(',', '，') for t in title]
    price = div.xpath('./dl/dd[last()]/div/span/text()')
    money = div.xpath('./dl/dd[last()]/div[2]/text()')
    area = div.xpath('./dl/dd[2]/span[3]/text()')
    huxing = div.xpath('./dl/dd[2]/span[1]/text()')
    print(title, price,money,area,huxing)
    info = []
    info.extend(title)
    info.extend(price)
    info.extend(money)
    info.extend(area)
    info.extend(huxing)
    print(info,'----------------')
    info_str = ",".join(info)
    print(info_str,'++++++++++++++++++')
    print('\n')
    write_file(info_str)

['通州政府旁精装两居室总价66万，安贞医院北关东夏'] ['66', '万'] ['11000元/㎡'] ['60.00㎡'] ['2室1厅1卫']
['通州政府旁精装两居室总价66万，安贞医院北关东夏', '66', '万', '11000元/㎡', '60.00㎡', '2室1厅1卫'] ----------------
通州政府旁精装两居室总价66万，安贞医院北关东夏,66,万,11000元/㎡,60.00㎡,2室1厅1卫 ++++++++++++++++++


['草桥欣园三区 复式 精装修业主自住 南北通透 采'] ['620', '万'] ['47187元/㎡'] ['131.39㎡'] ['4室3厅2卫']
['草桥欣园三区 复式 精装修业主自住 南北通透 采', '620', '万', '47187元/㎡', '131.39㎡', '4室3厅2卫'] ----------------
草桥欣园三区 复式 精装修业主自住 南北通透 采,620,万,47187元/㎡,131.39㎡,4室3厅2卫 ++++++++++++++++++


['通州宋庄现房 均价1万 不户籍 紧邻地铁6号线 '] ['45', '万'] ['14062元/㎡'] ['32.00㎡'] ['1室1厅1卫']
['通州宋庄现房 均价1万 不户籍 紧邻地铁6号线 ', '45', '万', '14062元/㎡', '32.00㎡', '1室1厅1卫'] ----------------
通州宋庄现房 均价1万 不户籍 紧邻地铁6号线 ,45,万,14062元/㎡,32.00㎡,1室1厅1卫 ++++++++++++++++++


['（中）固安孔雀城新机场首付25万 紧邻地铁口 5'] ['98', '万'] ['12405元/㎡'] ['79㎡'] ['2室2厅1卫']
['（中）固安孔雀城新机场首付25万 紧邻地铁口 5', '98', '万', '12405元/㎡', '79㎡', '2室2厅1卫'] ----------------
（中）固安孔雀城新机场首付25万 紧邻地铁口 5,98,万,12405元/㎡,79㎡,2室2厅1卫 ++++++++++++++++++


['南口楼房~采光好~格局好~环境优美~观景房'] ['140', '万'] ['25735元

### numpy库 数据分析基础

In [83]:
import numpy as np

In [43]:
data1 = np.array([1,2,3,4,5,6])  # 创建一维数组
data2 = np.array([[1,2,3,4],[4,5,6,7]])  # 创建2维数组  每个维度的长度需要长度一样
data00 = np.zeros(10) # 创建10个数值为0的数组，初始化用
data01 = np.ones(10) # 创建10个数值为0的数组，初始化用
data21 = np.ones((3,10)) # 创建二维数组，3行10列
dataAR = np.arange(10) # 创建0到9的数组

In [45]:
print(data2)
print(data2.ndim)  # 判断数组维度
print(data2.shape)  # 判断数组各维度的长度
type(data2)
print(data00)
print(data01)
print(data21)
print(dataAR[9]) # 获取数组中某个数字，索引
data2qp = data2[1][3]
print(data2qp) # 第二行第四列的数字, 切片得到的数据是原始的数据，data2qp的数据会同步改变data2里的数据
data2qp_copy = data2[1][3].copy()
print('data2qp_copy：',data2qp_copy)
print(data2[1,3])  # 同上
print(data1[0:2])

[[1 2 3 4]
 [4 5 6 7]]
2
(2, 4)
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]
9
7
data2qp_copy： 7
7
[1 2]


In [60]:
# 变换数组维度
data = np.arange(10)
print(data)
print(data.reshape((2,5))) # 数组需要一一对应性，如果上面arange(10)改为9 则会报错
print(data.reshape((2,5)).T) # 距阵转置,T必须大写，用的不多
print(data.reshape((5,2))) # 变成5行2列,T必须大写
print(np.sqrt(data))  # 求平方根

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[ 0.          1.          1.41421356  1.73205081  2.          2.23606798
  2.44948974  2.64575131  2.82842712  3.        ]


### ndarray常用方法
- abs 计算绝对值
- sqrt 计算平方根
- square 计算平方
- exp 计算指数ex
- sign 计算正负号：1，0，-1
- ceil 计算大于该元素的最小整数（向上取整数，进一位）
- floor 计算小于该元素的最大整数（向下取整，舍去小数位）
- isnan 计算是否非数字

In [64]:
# 数组相加
data1 = np.arange(10)
data2 = np.arange(10)
print(data1+data2) # data1+data2 对应两两相加
print(np.add(data1,data2)) # 同上 data1+data2

[ 0  2  4  6  8 10 12 14 16 18]
[ 0  2  4  6  8 10 12 14 16 18]


### 常用两个数组可用的方法
- add 两个数组相加
- subtract 两数组相减去
- multiply 两数组相相乘（不是距阵乘法）
- divide 两数组相除
- power 第一个数据元素A，第二数组元素B，计算A的B次方
- fmax 计算两个元素各个位置上最大的那个
- fmin 计算两个元素各个位置上最小的那个
- sum 计算所有元素的和
- mean 计算所有元素的平均值
- std 计算所有元素的标准差
- min,mix 计算所有元素的最大，最小值
- argmin,argmax 计算所有元素的最大，最小值的位置
- .sort 反序排序

In [70]:
data = np.arange(1,101)
data_sum = data.sum()
data_mean = data.mean()
print(data_sum,data_mean)

5050 50.5


In [ ]:
data = np.genfromtxt('data.txt',delimiter=',') # 以，作为分隔符读取data.txt里的数据
print(data)
print(data.astype(int)) # 把读取到的数字转换为整型

### 作业：读取rating.txt中的数据并分析
- 共有10000本书，以数字id表示
- 每个用户打分1-5
- 每一行数字有3个数字，分别是用户ID，书本ID，该用户对书的打分
#### 要求输出所有书本各自的平均得分



In [140]:
import numpy as np
path = r'C:\Users\10746\Desktop\ptthon-test\数据分析\数据分析项目2-2\rating.txt'
data = np.genfromtxt(path,delimiter=',')
data = data.astype(int)

In [141]:
rating_sum = np.zeros(10000)
rating_people_count = np.zeros(10000)

In [142]:
for rating in data:
    book_id = rating[1]-1
    rating_sum[book_id] += rating[2]
    rating_people_count[book_id]+=1
print(rating_sum/rating_people_count)

[ 4.27970709  4.35135011  3.21434056 ...,  4.32352941  3.70769231
  4.00900901]


# Pandas基础

In [3]:
import pandas as pd

In [4]:
data = pd.Series([2,3,33,55])  # 创建Series类型数据
print(data)
print(data.values) # 获取数据的值
print(data.index)  # 获取索引
list_data = [11,22,33,34]
data_exp = pd.Series(list_data,index=['a','b','c','d']) # 创建特殊索引
print(data_exp)
data_exp.index = ['j','a','c','d'] # 重新修改索引
print(data_exp)

0     2
1     3
2    33
3    55
dtype: int64
[ 2  3 33 55]
RangeIndex(start=0, stop=4, step=1)
a    11
b    22
c    33
d    34
dtype: int64


In [5]:
print(len(data_exp))  # 获取长度
print(data_exp['a'])  # 获取某个数据
print(data_exp[['a','c']])  # 获取数组中的多个数据
print(data_exp[0:2]) # 获取范围数据

j    11
a    22
c    33
d    34
dtype: int64
4
22
a    22
c    33
dtype: int64
j    11
a    22
dtype: int64


In [12]:
list_data = [11,22,33,34,33,33,44,55,55]
list_data = pd.Series(list_data)
print(list_data.value_counts()) # 计算元素出现的次数
print(1 in list_data)  # 判断索引是否在列表里

33    3
55    2
44    1
11    1
22    1
34    1
dtype: int64
True


In [24]:
dict_data={
    "A":100,
    "B":200,
    "C":30,
    "D":200
}
dict_data = pd.Series(dict_data,index=['A','B','C','E','F']) 
print(dict_data)  # 可以通过字典来创建序列类型
print(dict_data.isnull())  # isnull() 检测数据书否缺失  非空用notnull()
dict_data.name = 'ABC'  # 定义对象名称
dict_data.index.name = 'ABCef'  # 定义索引名称
print(dict_data)

A    100.0
B    200.0
C     30.0
E      NaN
F      NaN
dtype: float64
A    False
B    False
C    False
E     True
F     True
dtype: bool
ABCef
A    100.0
B    200.0
C     30.0
E      NaN
F      NaN
Name: ABC, dtype: float64


In [48]:
dict_data = {
    'student':['lilei','hanmeimei','madongmei'],
    'score':[100,80,33],
    'gender':['M','F','F']
}
dict_data = pd.DataFrame(dict_data)  # 创建DataFrame 数据类型
print(dict_data)
dict_data = pd.DataFrame(dict_data,columns=['gender','student','score'])  # 定义列的顺序
print(dict_data)
print(dict_data.columns) # 获取列头名称
print('student:\n',dict_data.student)  # 获取student列的值
print('student:\n',dict_data['student'])  # 获取student列的值,同上
print('iloc[0]:\n',dict_data.iloc[1]) # 获取行的数据 ，从第二行开始  头不算，
# print('student:\n',dict_data.loc['a']) # 特殊索引使用

  gender  score    student
0      M    100      lilei
1      F     80  hanmeimei
2      F     33  madongmei
  gender    student  score
0      M      lilei    100
1      F  hanmeimei     80
2      F  madongmei     33
Index(['gender', 'student', 'score'], dtype='object')
student:
 0        lilei
1    hanmeimei
2    madongmei
Name: student, dtype: object
student:
 0        lilei
1    hanmeimei
2    madongmei
Name: student, dtype: object
iloc[0]:
 gender             F
student    hanmeimei
score             80
Name: 1, dtype: object


In [58]:
dict_data = {
    'student':['lilei','hanmeimei','madongmei'],
    'score':[100,80,33],
    'gender':['M','F','F']
}
dict_data = pd.DataFrame(dict_data)  # 创建DataFrame 数据类型
print(dict_data,'\n')
slice_data = dict_data['score']
print(slice_data,'\n')   
slice_data[0] = 66666  # 修改切片出来的数据会同步影响原始数据
print(dict_data)  

  gender  score    student
0      M    100      lilei
1      F     80  hanmeimei
2      F     33  madongmei 

0    100
1     80
2     33
Name: score, dtype: int64 

  gender  score    student
0      M  66666      lilei
1      F     80  hanmeimei
2      F     33  madongmei


C:\Users\10746\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.


In [60]:
dict_data = {
    'student':['lilei','hanmeimei','madongmei'],
    'score':[100,80,33],
    'gender':['M','F','F']
}
dict_data = pd.DataFrame(dict_data)  # 创建DataFrame 数据类型
print(dict_data,'\n')
slice_data = dict_data['score'].copy()  # .copy后修改切片不会影响原来的数据
print(slice_data,'\n')   
slice_data[0] = 66666  
print(dict_data,'\n')  
print(slice_data,'\n')  

  gender  score    student
0      M    100      lilei
1      F     80  hanmeimei
2      F     33  madongmei 

0    100
1     80
2     33
Name: score, dtype: int64 

  gender  score    student
0      M    100      lilei
1      F     80  hanmeimei
2      F     33  madongmei 

0    66666
1       80
2       33
Name: score, dtype: int64 



In [63]:
dict_data = {
    'student':['lilei','hanmeimei','madongmei'],
    'score':[100,80,33],
    'gender':['M','F','F']
}
dict_data = pd.DataFrame(dict_data)  # 创建DataFrame 数据类型
dict_data['score'] = range(95,98)   #  通过range修改列的数据
print(dict_data)

  gender  score    student
0      M     95      lilei
1      F     96  hanmeimei
2      F     97  madongmei


In [66]:
dict_data = {
    'student':['lilei','hanmeimei','madongmei'],
    'score':[100,80,33],
    'gender':['M','F','F']
}
dict_data = pd.DataFrame(dict_data,index=['a','b','c']) 
score = pd.Series([111,222,333],index=['a','b','c'])  
dict_data['score'] = score # 直接获取另一个系列的数据值
print(dict_data)

  gender  score    student
a      M    111      lilei
b      F    222  hanmeimei
c      F    333  madongmei


In [74]:
dict_data = {
    'student':['lilei','hanmeimei','madongmei'],
    'score':[100,80,33],
    'gender':['M','F','F']
}
dict_data = pd.DataFrame(dict_data,index=['a','b','c']) 
del dict_data['score']  # 删除某列
print(dict_data,'\n')
# 排列列表,fill_value=0,无数值的 默认为0，不设置fill_value 则默认为NaN
dict_data = dict_data.reindex(['c','b','a','d'],fill_value = 0)  
print(dict_data)


  gender    student
a      M      lilei
b      F  hanmeimei
c      F  madongmei 

  gender    student
c      F  madongmei
b      F  hanmeimei
a      M      lilei
d      0          0


In [87]:
dict_data = {
    'student':['lilei','hanmeimei','madongmei'],
    'score':[100,80,22],
    'gender':['M','F','F']
}
dict_data = pd.DataFrame(dict_data,index=['a','b','c']) 
# 排列列表,method=ffill,从前面计算插值
dict_data = dict_data.reindex(['c','b','a','d'],method='ffill')
print(dict_data,'\n')
# 排列列表,method=bfill,从后面计算插值
# dict_data = dict_data.reindex(['c','b','a','d'],method='bfill')
# print(dict_data,'\n')

  gender  score    student
c      F     22  madongmei
b      F     80  hanmeimei
a      M    100      lilei
d      F     22  madongmei 



In [98]:
dict_data = {
    'student':['lilei','hanmeimei','madongmei'],
    'score':[100,80,22],
    'gender':['M','F','F']
}
dict_data = pd.DataFrame(dict_data,index=['a','b','c']) 
dict_data = dict_data.reindex(['c','b','a','d'])
print(dict_data,'/\n')
print(dict_data.dropna())  # .dropna() 删除有一个缺失数据的行
# print(dict_data.dropna(how='all'))  #  删除整行数据都缺失的行
# print(dict_data.fillna(0))  # 默认无数据的地方为0
# print(dict_data.fillna({'gender':'M','student':'unknown'}))  # 指定列填入不同数值
# dict_data = dict_data.drop('d') # 删除索引 为 d 行的数据

  gender  score    student
c      F   22.0  madongmei
b      F   80.0  hanmeimei
a      M  100.0      lilei
d    NaN    NaN        NaN /

  gender  score    student
c      F   22.0  madongmei
b      F   80.0  hanmeimei
a      M  100.0      lilei


### dict_data['score']>=90  常用数据筛选

In [102]:
dict_data = {
    'student':['lilei','hanmeimei','madongmei'],
    'score':[100,80,22],
    'gender':['M','F','F']
}
dict_data = pd.DataFrame(dict_data,index=['a','b','c']) 
dict_data = dict_data.reindex(['c','b','a','d'])
print(dict_data['score']>=90)   # 返回切片索引对应的真假
print()
print(dict_data[dict_data['score']>=90])   # 筛选数据 score 大于90的
print()
select_list = [100,22]
print(dict_data[dict_data['score'].isin(select_list)]) # 筛选数据 score 里包含 select_list 的

c    False
b    False
a     True
d    False
Name: score, dtype: bool

  gender  score student
a      M  100.0   lilei

  gender  score    student
c      F   22.0  madongmei
a      M  100.0      lilei


### 同id求和等计算

In [41]:
import pandas as pd
data = pd.DataFrame({
    'tag_id':['a','b','c','a','a','c'],
    'count':[10,30,20,10,15,22]
})
grouped_data = data.groupby('tag_id')  # 聚合函数 .groupby('id’)
print(grouped_data.sum())  # 同id求和   也可以求mean 等
print(grouped_data)  # 这样无法直接输出数值

        count
tag_id       
a          35
b          30
c          42


In [12]:
print(data.sort_index(),'\n')  # 对索引名称进行排序
print(data.sort_index(ascending=False),'\n')  # 倒叙
print(data.sort_values(by='count'),'\n')  # 按照某一列进行排序

   count tag_id
0     10      a
1     30      b
2     20      c
3     10      a
4     15      a
5     22      c 

   count tag_id
5     22      c
4     15      a
3     10      a
2     20      c
1     30      b
0     10      a 

   count tag_id
0     10      a
3     10      a
4     15      a
2     20      c
5     22      c
1     30      b 



### Pandas常用方法
- count 计算非NaN数据的数量
- min,max 计算最小，最值大
- argmin,argmax 计算最小，最大值的位置
- sum 计算和
- mean 计算平均值
- median 计算中位数
- var 计算方差
- std 计算标准差


### Pandas数据合并

In [25]:
import pandas as pd
data1 = pd.DataFrame({
    'key':['a','b','a','c','b','d'],
    'data1':[1,2,3,4,5,6]
})
data2 = pd.DataFrame({
    'key':['a','b','c'],
    'data2':[8,9,7]
})
print(pd.merge(data1,data2))  # 自动合并取【交集】，多出的d 会被自动去除

   data1 key  data2
0      1   a      8
1      3   a      8
2      2   b      9
3      5   b      9
4      4   c      7


In [19]:
print(pd.merge(data1,data2,how='outer'))   # how='outer' ，取【并集】，没有数据的默认为NaN

   data1 key  data2
0      1   a    8.0
1      3   a    8.0
2      2   b    9.0
3      5   b    9.0
4      4   c    7.0
5      6   d    NaN


In [20]:
print(pd.merge(data1,data2,how='left'))   # 以左边’data1‘为标准

   data1 key  data2
0      1   a    8.0
1      2   b    9.0
2      3   a    8.0
3      4   c    7.0
4      5   b    9.0
5      6   d    NaN


In [21]:
print(pd.merge(data1,data2,how='right')) # 以右边’data2‘为标准

   data1 key  data2
0      1   a      8
1      3   a      8
2      2   b      9
3      5   b      9
4      4   c      7


In [28]:
print(pd.merge(data1,data2,on='key',how='outer')) #  on='key'指定列名称进行合并

   data1 key  data2
0      1   a    8.0
1      3   a    8.0
2      2   b    9.0
3      5   b    9.0
4      4   c    7.0
5      6   d    NaN


In [31]:
import pandas as pd
data1 = pd.DataFrame({
    'lkey':['a','b','a','c','b','d'],
    'data1':[1,2,3,4,5,6]
})
data2 = pd.DataFrame({
    'rkey':['a','b','c'],
    'data2':[8,9,7]
})
print(pd.merge(data1,data2,left_on='lkey',right_on='rkey',how='outer'))  # 列名不同时，指定多个列名合并

   data1 lkey  data2 rkey
0      1    a    8.0    a
1      3    a    8.0    a
2      2    b    9.0    b
3      5    b    9.0    b
4      4    c    7.0    c
5      6    d    NaN  NaN


### Pandas 读取文件
- data = pd.read_csv(f,header=None) # 不需要标题行
- data = pd.read_csv(f,names=['user_id,'book_id']) # 指定标题行名称
- data = pd.read_csv(f,index='user_id') # 指定索引列
- data = pd.read_csv(f,sep=',') # 指定分隔符

In [46]:
import pandas as pd
path_read = r'C:\Users\10746\Desktop\ptthon-test\数据分析\数据分析项目2-1\books.csv'
path_save = r'C:\Users\10746\Desktop\pandas_save.csv'  # 设置保存的路径
f = open(path,encoding='utf-8')  # 路径带有中文的时候 要先打开才能用pd读取
data = pd.read_csv(f)
# print(data)  # 默认把第一行作为标题名称
data.to_csv(path_save)

In [49]:
path_excel = r'C:/Users/10746/Desktop/聚店长运营数据.xlsx'
file = pd.ExcelFile(path_excel)  # 填入路径
data = file.parse('2019年')  # '2019年'为要读取的sheet的名称
print(data)

                     时间  新增扫码订单数  续订扫码订单数   扫码订单总数     扫码订单总金额  自然新增订单数  \
0   2019-01-01 00:00:00   1492.0     21.0   1513.0    94892.88    300.0   
1   2019-02-01 00:00:00   5321.0     27.0   5348.0   321329.00    386.0   
2   2019-03-01 00:00:00  13699.0     28.0  13727.0   831010.81    586.0   
3   2019-04-01 00:00:00   3867.0     49.0   3916.0   245419.96   2565.0   
4   2019-05-01 00:00:00   3740.0     76.0   3816.0   246391.00   1864.0   
5   2019-06-01 00:00:00   4492.0     90.0   4582.0   286975.00   1608.0   
6   2019-07-01 00:00:00   5295.0     68.0   5363.0   340839.00    903.0   
7   2019-08-01 00:00:00   4508.0    528.0   5036.0   329795.00    916.0   
8   2019-09-01 00:00:00   2630.0    507.0   3137.0   200637.34    796.0   
9                    合计  45044.0   1394.0  46438.0  2897289.99   9924.0   
10                  NaN      NaN      NaN      NaN         NaN      NaN   
11                  NaN      NaN      NaN      NaN         NaN      NaN   
12                  NaN  

### 作业 分析热门标签
- 任务1:找出最多人想读的50本书的名称 
- 任务2:找出这50本书对应最热门的10个标签
- 文件 1: to_read.csv
- 每行两个数据，用户id和该用户想读的书籍id 
- 文件2: books.csv 
- 书籍的各类id,名称，作者等信息 
- 文件3: tags.csv
- 每行两个数据，标签id和标签名称 
- 文件4: book_tags.csv
- 每行三个数据，_goodreads_book_id_ (和to_read中的书籍  
id的对应关系可以在books.csv里找到）标签id,标记次数

In [53]:
import pandas as pd
path_to_read = r'C:\Users\10746\Desktop\ptthon-test\数据分析\to_read.csv'
path_books = r'C:\Users\10746\Desktop\ptthon-test\数据分析\books.csv'
path_hot50_title_save= r'C:\Users\10746\Desktop\ptthon-test\数据分析\hottest_50_books_with_title.csv'
path_book_tags = r'C:\Users\10746\Desktop\ptthon-test\数据分析\book_tags.csv'
path_tags = r'C:\Users\10746\Desktop\ptthon-test\数据分析\tags.csv'
path_hot10_with_tag_name_save = r'C:\Users\10746\Desktop\ptthon-test\数据分析\path_hot10_with_tag_name.csv'

In [54]:
f = open(path_to_read,encoding='utf-8')  # 路径带有中文的时候 要先打开才能用pd读取
to_read = pd.read_csv(f)
# .value_counts()  计算元素出现的次数
# .sort_values(ascending=False) 以降序排序，最热门的书在最上面
to_read_counts = to_read['book_id'].value_counts().sort_values(ascending=False)
print(to_read_counts)

47      2772
143     1967
113     1840
13      1812
11      1767
45      1717
139     1650
39      1619
65      1608
35      1576
342     1521
185     1502
119     1499
8       1498
6       1484
4       1478
94      1460
89      1458
55      1441
61      1435
109     1432
16      1425
31      1417
67      1352
146     1342
54      1339
46      1325
121     1313
5       1293
173     1292
        ... 
6345       1
9818       1
8746       1
3279       1
5878       1
8946       1
9124       1
9665       1
9125       1
6656       1
9838       1
9230       1
9724       1
9239       1
9739       1
6841       1
4869       1
8699       1
8774       1
7951       1
9248       1
9858       1
6297       1
3936       1
9796       1
9345       1
9803       1
3662       1
4434       1
9781       1
Name: book_id, Length: 9986, dtype: int64


In [55]:
# 获取前50个的bookid
hottest_50_books_id = to_read_counts[:50].index  
print(hottest_50_books_id)

Int64Index([ 47, 143, 113,  13,  11,  45, 139,  39,  65,  35, 342, 185, 119,
              8,   6,   4,  94,  89,  55,  61, 109,  16,  31,  67, 146,  54,
             46, 121,   5, 173, 115,  68,  36,  95, 167, 129, 265, 137, 277,
             66, 267, 268,  28,  38,  60,  14, 225,  10, 233, 252],
           dtype='int64')


In [56]:
# 获取前50个的bookid出现的次数
hottest_50_books_counts = to_read_counts[:50].values
print(hottest_50_books_counts)

[2772 1967 1840 1812 1767 1717 1650 1619 1608 1576 1521 1502 1499 1498 1484
 1478 1460 1458 1441 1435 1432 1425 1417 1352 1342 1339 1325 1313 1293 1292
 1285 1257 1211 1208 1188 1181 1180 1172 1160 1158 1154 1149 1148 1130 1129
 1127 1111 1110 1106 1105]


In [57]:
# 转换数据类型
hottest_50_books = pd.DataFrame({
    'book_id':hottest_50_books_id,
    'to_read_counts':hottest_50_books_counts
})
print(hottest_50_books)

    book_id  to_read_counts
0        47            2772
1       143            1967
2       113            1840
3        13            1812
4        11            1767
5        45            1717
6       139            1650
7        39            1619
8        65            1608
9        35            1576
10      342            1521
11      185            1502
12      119            1499
13        8            1498
14        6            1484
15        4            1478
16       94            1460
17       89            1458
18       55            1441
19       61            1435
20      109            1432
21       16            1425
22       31            1417
23       67            1352
24      146            1342
25       54            1339
26       46            1325
27      121            1313
28        5            1293
29      173            1292
30      115            1285
31       68            1257
32       36            1211
33       95            1208
34      167         

In [58]:
# 获取books.csv的这三列'book_id','goodreads_book_id','title'
f = open(path_books,encoding='utf-8')  # 路径带有中文的时候 要先打开才能用pd读取
books = pd.read_csv(f)
book_id_and_title = books[['book_id','goodreads_book_id','title']]
print(book_id_and_title)  

      book_id  goodreads_book_id  \
0           1            2767052   
1           2                  3   
2           3              41865   
3           4               2657   
4           5               4671   
5           6           11870085   
6           7               5907   
7           8               5107   
8           9                960   
9          10               1885   
10         11              77203   
11         12           13335037   
12         13               5470   
13         14               7613   
14         15              48855   
15         16            2429135   
16         17            6148028   
17         18                  5   
18         19                 34   
19         20            7260188   
20         21                  2   
21         22           12232938   
22         23              15881   
23         24                  6   
24         25             136251   
25         26                968   
26         27               

In [59]:
# 以'book_id' 以 hottest_50_books 为准（left）， 合并数据
hottest_50_books_with_title = pd.merge(
    hottest_50_books,
    book_id_and_title,
    on = 'book_id',
    how = 'left')
print(hottest_50_books_with_title)
hottest_50_books_with_title.to_csv(path_hot50_title_save)

    book_id  to_read_counts  goodreads_book_id  \
0        47            2772              19063   
1       143            1967           18143977   
2       113            1840             168668   
3        13            1812               5470   
4        11            1767              77203   
5        45            1717               4214   
6       139            1650            9460487   
7        39            1619              13496   
8        65            1608               4981   
9        35            1576                865   
10      342            1521           13497818   
11      185            1502            9361589   
12      119            1499              38447   
13        8            1498               5107   
14        6            1484           11870085   
15        4            1478               2657   
16       94            1460                320   
17       89            1458              21787   
18       55            1441               5129   


In [68]:
f = open(path_book_tags,encoding='utf-8')  
book_tags = pd.read_csv(f)  # 读取book_tags文件
# 如果 '_goodreads_book_id_' 列的值在 goodreads_book_id列里，则把数据给到 book_tags
book_tags = book_tags[book_tags['_goodreads_book_id_'].isin(hottest_50_books_with_title['goodreads_book_id'])]
del book_tags['_goodreads_book_id_'] # 删除 _goodreads_book_id_ 列
hottest_10_tags = book_tags.groupby('tag_id').sum()  # tag_id 列 每个tag_id的值求和
print(hottest_10_tags)

        count
tag_id       
236      5802
240      9649
248       113
251      4006
254       623
392       160
414       422
420       288
442       312
450       754
461        92
473        43
509      1938
603       156
617       283
671        79
686        40
698       182
711       149
718        29
719        21
722       673
736       704
747        79
751      1269
766       850
767       125
770       144
780       473
781       857
...       ...
32130    7684
32514      54
32586    7597
32686    1379
32688      27
32724     132
32799     104
32808     853
32812    1796
32820     100
32906    1462
32917    3363
32973      76
32989   29521
32996    1121
33004     623
33006      76
33009     878
33012    2488
33023    1361
33046     142
33114   56829
33116     132
33124    1722
33125     150
33127     108
33153     133
33777    1330
34248    4310
34251     384

[758 rows x 1 columns]


In [61]:
# 按照倒序（由多到少）排列取 前10个
hottest_10_tags = hottest_10_tags.sort_values(by='count',ascending=False)[:10]
print(hottest_10_tags)

          count
tag_id         
30574   6061902
8717     412677
11557    404973
11743    299256
7457     279578
14487     80671
11305     71863
5207      71629
22743     65001
33114     56829


In [69]:
f = open(path_tags,encoding='utf-8')
tags = pd.read_csv(f)

In [70]:
hottest_10_tags_with_tag_name = pd.merge(
    hottest_10_tags,
    tags,
    on = 'tag_id',
    how = 'left')
print(hottest_10_tags_with_tag_name)
#  在PYcharm 用3.8 就不会报错

KeyError: 'tag_id'

In [12]:
hottest_10_tags_with_tag_name.to_csv(path_hot10_with_tag_name_save)

NameError: name 'hottest_10_tags_with_tag_name' is not defined

# Pyecharts 基础

In [12]:
# !pip install pyecharts 
# !pip install cutecharts # 可爱类型的图型风格 
https://github.com/chenjiandongx/cutecharts

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple


### 图表绘制流程
- char_name = 图表类型() 初始化类型图表
- chart_name.add_xaxis() 添加横坐标名称/数据
- chart_name.add_xaxis() 添加纵坐标名称/数据
- chart_name.render() 生成.html文件

In [2]:
from pyecharts.faker import Faker  # 创建虚构随机数据用
from pyecharts import options as opts   # 设置参数的库
from pyecharts.globals import ThemeType # 配置主题的库

from pyecharts.charts import Bar   # 柱状图的库
from pyecharts.charts import Bar3D  # 3D柱状图
from pyecharts.charts import Line # 折线图的库
from pyecharts.charts import Pie # 饼图的库
from pyecharts.charts import EffectScatter # 带涟漪的散点图
from pyecharts.charts import Funnel # 漏斗图
from pyecharts.charts import Geo # 地理图 
from pyecharts.charts import Liquid # 水球图
from pyecharts.charts import Radar # 雷达图
from pyecharts.charts import WordCloud # 词云图

### 作业
#### 任务1：将50本书及对应想读的人数数据做成词云图
#### 任务2：选择两种你认为适合10个热门标签进行数据展示的图表类型作图

In [1]:
from pyecharts import options as opts
from pyecharts.charts import WordCloud # 词云图
from pyecharts.charts import Bar   # 柱状图的库
from pyecharts.charts import Pie # 饼图的库
import pandas as pd

SyntaxError: invalid syntax (<ipython-input-1-4d69597cd706>, line 6)

In [8]:
# 任务1 读取文件
path_worldcloud =  r'C:\Users\10746\Desktop\ptthon-test\数据分析\hottest_50_books_with_title.csv'
f = open(path_worldcloud)
hottest_50_books = pd.read_csv(f)

In [9]:
title = hottest_50_books['title'].tolist()
to_read_counts = hottest_50_books['to_read_counts'].tolist()
cloud_max = list(zip(title,to_read_counts))

In [10]:
# 词云
worldcloud = WordCloud()
worldcloud.add('',cloud_max,word_size_range=[20,100])
worldcloud.set_global_opts(title_opts = opts.TitleOpts(title='hottest_50_books'))
worldcloud.render()

'C:\\Users\\10746\\render.html'

In [11]:
# 任务2
# 读取文件
path_hot10 =  r'C:\Users\10746\Desktop\ptthon-test\数据分析\path_hot10_with_tag_name.csv'
f = open(path_hot10,encoding='utf-8')
hottest_10_books = pd.read_csv(f)

In [12]:
# 柱状图
bar = Bar(
    init_opts = opts.InitOpts(
#         theme = ThemeType.PURPLE_PASSION,
        width = '1280px',
        height = '720px'))
bar.add_xaxis(hottest_10_books['tag_name'].tolist())
bar.add_yaxis('',hottest_10_books['count'].tolist())
bar.set_global_opts(
    title_opts = opts.TitleOpts(title = "hottest_10_tag_name"),
    xaxis_opts = opts.AxisOpts(axislabel_opts=opts.LabelOpts(rotate = 10)))
bar.render()

'C:\\Users\\10746\\render.html'

In [13]:
# 饼状图
pie = Pie()
pie_tag_name = hottest_10_books['tag_name'].tolist()
pie_count = hottest_10_books['count'].tolist()
pie_max = list(zip(pie_tag_name,pie_count))
pie.add("",pie_max)
pie.render()

'C:\\Users\\10746\\render.html'

### 数据分析及可视化实战
- https://github.com/fxsjy/jieba 结巴分词

In [1]:
import sqlite3  # 链接数据库的库
import pandas as pd  
import jieba  # 分词用的库
import pyecharts.options as opts   # 设置参数的库
from pyecharts.charts import HeatMap  # 热力图库
from pyecharts.charts import WordCloud # 词云图
from pyecharts.charts import Bar   # 柱状图的库
import math  # 数学库
import os

In [2]:
# 用来过滤的词
FILTER_WORDS=['知道','影评','电影','影片','片子','这么','那么',
              '怎么','是','的','这个','那个','一个','这种','时候',
              '什么','\n','...','一部','这部','没有','还有','is','觉得','of','to']

In [3]:
# 定义一个 输入最小评论数返回电影ID的函数
def get_movie_id_list(min_comment_count):
    movie_list = comment_data['MOVIEID'].value_counts() # 获取每个电影ID对应的评论总数
    movie_list = movie_list[movie_list.values > min_comment_count] # 取大于min_comment_count的数据
    return movie_list.index  # 返回电影ID

In [4]:
# 定义一个根据电影ID获取前count个热门电影评论词的函数 
def get_comment_keywords_count(movie_id,count):  
    comment_list = comment_data[comment_data['MOVIEID'] == movie_id]['CONTENT']
    comment_str_all = ''  # 创建一个str
    for comment in comment_list:  # 遍历ID对应的所有的评论
        comment_str_all += comment + '\n'   # 把评论放到一个str里
    seg_list = list(jieba.cut(comment_str_all)) # 对str进行分词并变为列表类型
    keywords_counts = pd.Series(seg_list)   # 把上面的列表变为 Series 类型
    keywords_counts = keywords_counts[keywords_counts.str.len()>1]  # 筛选分词后长度大于1的词
    # .contains('需要选取的内容')   
    # '|'.join(FILTER_WORDS)  FILTER_WORDS里以|隔开取隔开后 包含的数据 ,
    #  ~ 波浪线是取反  即 不包含
    keywords_counts = keywords_counts[~keywords_counts.str.contains('|'.join(FILTER_WORDS))] 
    keywords_counts = keywords_counts.value_counts()[:count]                         
    return keywords_counts

In [5]:
# 需要读取的数据
path_douban = r'C:\Users\10746\Desktop\ptthon-test\数据分析\数据分析项目2-1\douban_comment_data.db' 
path_movie_data = r'C:\Users\10746\Desktop\ptthon-test\数据分析\数据分析项目2-1\douban_movie_data.xlsx'
conn = sqlite3.connect(path_douban)  # 链接数据库  
comment_data = pd.read_sql_query('select * from comment;',conn)   # SQL语句 获取表格的全部数据
movie_data = pd.read_excel(path_movie_data) # 读取数据

In [6]:
# 生成词云的 并保存到本地的函数
def generate_word_cloud(word_list):
    wordcloud = WordCloud() 
    keywords_cloud = list(zip(keywords_counts.index,keywords_counts.values))
    lst = []
    for i in keywords_cloud:
        lst.append((i[0],int(i[1])))
    # path = r'C:\Users\10746\Anaconda3\Lib\site-packages\jupyterthemes\fonts\serif\georgiaserif\Lora-Regular.ttf'
    # wordcloud = WordCloud(font_path=path,background_color="white",width=800,height=600,max_font_size=50,max_words=1000)
    wordcloud.add("",lst,word_size_range = [20,100])
    path_name = r'C:\Users\10746\Desktop\wordcloud_{}_{}.html'.format(movie_name,movie_score)
    wordcloud.render(path_name)
    print(f'词云图 图片已经报保存到:{path_name}')

In [7]:
 # 保存为柱状图的函数，需要参数keywords_counts：数据源， path_name：保存地址
def generate_bar(keywords_counts):  
    bar = Bar(
        init_opts = opts.InitOpts(
#             theme = ThemeType.PURPLE_PASSION,
            width = '1280px',
            height = '720px'))
    bar.add_xaxis(keywords_counts.index.tolist())
    bar.add_yaxis('',keywords_counts.values.tolist())
    bar.set_global_opts(
        title_opts = opts.TitleOpts(title = movie_name),
        xaxis_opts = opts.AxisOpts(axislabel_opts=opts.LabelOpts(rotate = 20)))
    path_name = r'C:\Users\10746\Desktop\bar_{}_{}.html'.format(movie_name,movie_score)
    bar.render(path_name)
    print(f'柱状图 图片已经报保存到:{path_name}')

In [8]:
# 输入 movie_id 返回 movie_name,movie_score 电影名字和评分的函数
def get_movie_name_and_score(movie_id):
    movie_link = 'https://movie.douban.com/subject/{}/'.format(movie_id)
    search_result = movie_data[movie_data['链接'] == movie_link].iloc[0]
    movie_name = search_result['电影名']
    movie_score = search_result['评分']
    return(movie_name,movie_score)

In [9]:
movie_id = '1292052'
counts = 30 # 取前counts个关键词
keywords_counts = get_comment_keywords_count(movie_id,counts)
movie_name,movie_score = get_movie_name_and_score(movie_id)

Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\10746\AppData\Local\Temp\jieba.cache
Loading model cost 0.892 seconds.
Prefix dict has been built successfully.


In [10]:
generate_bar(keywords_counts)
generate_word_cloud(keywords_counts)

柱状图 图片已经报保存到:C:\Users\10746\Desktop\bar_肖申克的救赎_9.6.html
词云图 图片已经报保存到:C:\Users\10746\Desktop\wordcloud_肖申克的救赎_9.6.html


### 关键词及评分关系分析

In [11]:
kw_list_by_score = [[] for i in range(10)]  # 创建含有10个空列表的列表
kw_counts_list_by_score = [[] for i in range(10)]  # 创建含有10个空列表的列表

In [12]:
comment_counts = 300
count = 30
movie_id_list = get_movie_id_list(comment_counts)  # 获取有300个及以上评论的电影ID
for movie_id in movie_id_list:  # 遍历这些ID
    word_list = get_comment_keywords_count(movie_id,count)   # 获取ID对应的前counts个热门电影评论词和评论数
    movie_name,movie_score = get_movie_name_and_score(movie_id)   # 获取ID对应的电影名字和评分的函数
    # [1].extend[2]得[1,2] ,math.floor(1.9)==1
    # 可能 kw_list_by_score 不是数字，或无数据，需要try一下
    try:
        # 把 floor处理后的【评分】和评论关键词添加到 kw_list_by_score 列表
        kw_list_by_score[math.floor(movie_score)].extend(word_list.index)  
        # 把 floor处理后的【评分】和【评论数】添加到 kw_counts_list_by_score 列表
        kw_counts_list_by_score[math.floor(movie_score)].extend(word_list.values)
    except:  # 如果上面没有添加成功则输出 该电影ID
        print(movie_id)

10512661
22263645
25765735
6311303
25808075
26260853
26607693


In [23]:
path_movie = r'C:\Users\10746\Desktop\ptthon-test\数据分析\movie_keyword_by_score'

In [24]:
# 创建DataFrame数据
# 保存该得分区间的TOP30关键词和出现的总次数
for i in range(10):
    if kw_list_by_score[i]:
        kw30_with_counts = pd.DataFrame({
            'kw':kw_list_by_score[i],
            'counts':kw_counts_list_by_score[i]
        })
    # 统计关键词出现的次数，算出百分比 并存储
        kw30_with_counts = kw30_with_counts.groupby('kw').sum()
        kw30_with_counts = kw30_with_counts.sort_values(by='counts',ascending=False)[:30]
        counts_sum = kw30_with_counts['counts'].sum()
        kw30_with_counts['percentage'] = kw30_with_counts['counts']/counts_sum
        path = os.path.join(path_movie,'{}_movie_keywords.csv'.format(i))
        kw30_with_counts.to_csv(path)

In [25]:
print(kw30_with_counts,type(kw30_with_counts))

    counts  percentage
kw                    
喜欢    1356    0.092289
自己    1188    0.080855
故事     864    0.058804
最后     857    0.058327
经典     793    0.053971
我们     722    0.049139
可以     613    0.041721
感觉     610    0.041516
世界     595    0.040495
好看     485    0.033009
教父     472    0.032124
这样     465    0.031648
生活     455    0.030967
自由     437    0.029742
看到     424    0.028857
因为     418    0.028449
人生     411    0.027973
美国     373    0.025386
剧情     363    0.024706
导演     348    0.023685
小时     324    0.022051
爱情     278    0.018921
音乐     270    0.018376
感动     260    0.017696
其实     259    0.017627
诺兰     239    0.016266
阿甘     212    0.014429
男人     210    0.014293
励志     196    0.013340
人性     196    0.013340 <class 'pandas.core.frame.DataFrame'>


In [41]:
kw_counts_by_score = [[] for _ in range(10)] # 创建10个空列表

for i in range(4,10):  # 只取4到9分的内容
    path = os.path.join(path_movie,'{}_movie_keywords.csv'.format(i))
    f = open(path)
    kw_counts_by_score[i] = pd.read_csv(path,engine='python')  # engine='python' 

    kw_percentage_df = pd.DataFrame([],
        columns = list(range(4,10)),
        index = kw_counts_by_score[i]['kw'][:20])
print(kw_percentage_df)

      4    5    6    7    8    9
kw                              
喜欢  NaN  NaN  NaN  NaN  NaN  NaN
自己  NaN  NaN  NaN  NaN  NaN  NaN
故事  NaN  NaN  NaN  NaN  NaN  NaN
最后  NaN  NaN  NaN  NaN  NaN  NaN
经典  NaN  NaN  NaN  NaN  NaN  NaN
我们  NaN  NaN  NaN  NaN  NaN  NaN
可以  NaN  NaN  NaN  NaN  NaN  NaN
感觉  NaN  NaN  NaN  NaN  NaN  NaN
世界  NaN  NaN  NaN  NaN  NaN  NaN
好看  NaN  NaN  NaN  NaN  NaN  NaN
教父  NaN  NaN  NaN  NaN  NaN  NaN
这样  NaN  NaN  NaN  NaN  NaN  NaN
生活  NaN  NaN  NaN  NaN  NaN  NaN
自由  NaN  NaN  NaN  NaN  NaN  NaN
看到  NaN  NaN  NaN  NaN  NaN  NaN
因为  NaN  NaN  NaN  NaN  NaN  NaN
人生  NaN  NaN  NaN  NaN  NaN  NaN
美国  NaN  NaN  NaN  NaN  NaN  NaN
剧情  NaN  NaN  NaN  NaN  NaN  NaN
导演  NaN  NaN  NaN  NaN  NaN  NaN


In [42]:
for i in range(4,10):
    kw = kw_counts_by_score[i]
    kw = kw[kw['kw'].isin(kw_percentage_df.index)]
    kw_percentage_df[i] = pd.Series(list(kw['percentage']),index=kw['kw'])
kw_percentage_df.fillna(0,inplace = True)

In [43]:
# 设计图表需要的数据
# 由 x,y,z 三个坐标组成
data = []
i = 0
for index in kw_percentage_df.index:
    j = 0
    for column in kw_percentage_df.columns:
        data.append([j,i,kw_percentage_df[column][index]*100])
        j+=1
    i += 1

In [44]:
heatmap = HeatMap()
columns = list(range(4,10))
heatmap.add_xaxis(columns)
heatmap.add_yaxis("电影评论关键词热力图",list(kw_percentage_df.index),data)
heatmap.set_global_opts(
    visualmap_opts = opts.VisualMapOpts(
        min_ = 0,
        max_ = 10,
        orient = 'horizontal'
    ),
)
path = r'C:\Users\10746\Desktop\heatmap.html'
heatmap.render(path = path)

'C:\\Users\\10746\\Desktop\\heatmap.html'